### ISSUE TITLE
A question about `prompt_text_only`

### ISSUE THREAD

**Issue by louis-avo** [TencentARC/PhotoMaker#123]
Hi, thanks for your excellent work!

I have a question about the code for getting `prompt_text_only`: https://github.com/TencentARC/PhotoMaker/blob/3d5312add5bada9bf8756c857a3ea7413592e59a/photomaker/pipeline.py#L356-L360

I'm quite curious about why not just replace the trigger word with null character like：
```python
prompt_text_only = prompt.replace("img", "")
```

Looking forward to hearing from you soon!

**Comment by Paper99** [comment]
See this commit(https://github.com/TencentARC/PhotoMaker/issues/63) for more details

**Comment by louis-avo** [comment]
> See this commit(#63) for more details

Thanks!
