### ISSUE TITLE
试了一下,感觉自己对比照片变丑了好多

### ISSUE THREAD

**Issue by shine10076** [TencentARC/PhotoMaker#132]
有点伤心

**Comment by shine10076** [comment]
素人的效果感觉还需要提升,明星毕竟是明星,脸型好

**Comment by liuxuan111** [comment]
n

> 素人的效果感觉还需要提升,明星毕竟是明星,脸型好

你用的什么显卡，我用4090很丑，但是其他不会，在huggingface上的试用也不会，很奇怪不知道什么原因
