### ISSUE TITLE
inference is so slow

### ISSUE THREAD

**Issue by akk-123** [TencentARC/PhotoMaker#38]
run photomaker_demo code, inference with 2 input img, 40 steps, generete 4 img need 4 minutes on V100

**Comment by Paper99** [comment]
The speed is amazing. It only takes me less than 10 seconds to generate an image on the A100 with 10 input images.

**Comment by akk-123** [comment]
10 sencond? but I cost 4 minutes, and I'm sure the code runs on gpu
![image](https://github.com/TencentARC/PhotoMaker/assets/98469560/d0d1bc70-5633-4359-b76c-c3585be6f680)

**Comment by Paper99** [comment]
In principle, it is not much slower than sdxl.
How long does it take you to run sdxl?

**Comment by akk-123** [comment]
same config, run 40 steps, generate 4 img, cost 40s
![image](https://github.com/TencentARC/PhotoMaker/assets/98469560/47de1a16-1759-4085-97c7-e23d0240bb75)

**Comment by bmaltais** [comment]
Hummm... on a 3090 on windows it generate 4 images in 66 seconds

**Comment by chille9** [comment]
> Hummm... on a 3090 on windows it generate 4 images in 66 seconds @ 50 steps

Hi bmaltais, thanks for your work with this project. Do you know why it takes me 3+ hours to generate 2 images with default settings on a 2060 gpu? Any way to reduce the time.. by like 4000% haha?

**Comment by bmaltais** [comment]
This is certainly not normal... have you followed the installation instructions in my fork or are you using the default install instruction in the main repo?

Try following my instructions and see if it make a difference...

https://github.com/bmaltais/PhotoMaker/?tab=readme-ov-file#-dependencies-and-installation-windows

**Comment by chille9** [comment]
> Try following my instructions and see if it make a difference...
> 
> https://github.com/bmaltais/PhotoMaker/?tab=readme-ov-file#-dependencies-and-installation-windows

Right! It´s very weird and I´m so hyped to generate stuff.. ! I just tried a clean install of your fork AND python without using anaconda environment and adding python to path. 
Still seems to take forever. At least the gpu is at 100% as far as I can tell.

I did a quick test in comfy ui where 20 steps and 512px res takes 30 seconds.

Something fishy is certainly going down.

**Comment by bmaltais** [comment]
> > Try following my instructions and see if it make a difference...
> > https://github.com/bmaltais/PhotoMaker/?tab=readme-ov-file#-dependencies-and-installation-windows
> 
> Right! It´s very weird and I´m so hyped to generate stuff.. ! I just tried a clean install of your fork AND python, not using anaconda environments this time even tho it should technically work as well.
> 
> Still seems to take forever. At least the gpu is at 100% as far as I can tell.
> 
> I did a quick test in comfy ui where 20 steps and 512px res takes 30 seconds.
> 
> Something fishy is certainly going down.

Yeah... this is odd... I have pushed a PR to both ComfyUI nodes to add support for width and height... this should bring the ComfyUI support on par with Gradio. The nodes are still immature but hope things will improve so they become more standard ComfyUI nodes with proper batch image input support and multiple image outputs...

https://github.com/StartHua/Comfyui-Mine-PhotoMaker/pull/4

https://github.com/ZHO-ZHO-ZHO/ComfyUI-PhotoMaker/pulls

**Comment by chille9** [comment]
> > > Try following my instructions and see if it make a difference...
> > > https://github.com/bmaltais/PhotoMaker/?tab=readme-ov-file#-dependencies-and-installation-windows
> > 
> > 
> > Right! It´s very weird and I´m so hyped to generate stuff.. ! I just tried a clean install of your fork AND python, not using anaconda environments this time even tho it should technically work as well.
> > Still seems to take forever. At least the gpu is at 100% as far as I can tell.
> > I did a quick test in comfy ui where 20 steps and 512px res takes 30 seconds.
> > Something fishy is certainly going down.
> 
> Yeah... this is odd... I have pushed a PR to both ComfyUI nodes to add support for width and height... this should bring the ComfyUI support on par with Gradio. The nodes are still immature but hope things will improve so they become more standard ComfyUI nodes with proper batch image input support and multiple image outputs...
> 
> [StartHua/Comfyui-Mine-PhotoMaker#4](https://github.com/StartHua/Comfyui-Mine-PhotoMaker/pull/4)
> 
> [ZHO-ZHO-ZHO/ComfyUI-PhotoMaker#5](https://github.com/ZHO-ZHO-ZHO/ComfyUI-PhotoMaker/pull/5)

Thanks a bunch. Oh are you able to use ComfyUI somehow with photomaker? (might be a nooby question since im an amateur enthusiast) ^^. To clarify i used comfy with a standard and different model than this project.

**Comment by bmaltais** [comment]
Yes, you can use either of those ComfyUU photomaker nodes. The install is not straightforward but it works for me.

**Comment by chille9** [comment]
> Yes, you can use either of those ComfyUU photomaker nodes. The install is not straightforward but it works for me.

Oh damn thats super dope if it works as well as this project somehow. 

If you get time I´d love a couple of quick pointers on how to install that. Doesnt seem like they wrote how in the projects. 🥇 😶‍🌫️  No pressure.

**Comment by Paper99** [comment]
@akk-123 @chille9  An important note: For those GPUs that do not support bfloat16, please change [this line](https://github.com/TencentARC/PhotoMaker/blob/6ec44fc13909d64a65c635b9e3b6f238eb1de9fe/gradio_demo/app.py#L39) to torch_dtype = torch.float16, the speed will be greatly improved (1min/img (before) vs. 14s/img (after) on V100). The minimum GPU memory requirement for PhotoMaker is 15G.

**Comment by chille9** [comment]
> @akk-123 @chille9 change [this line](https://github.com/TencentARC/PhotoMaker/blob/6ec44fc13909d64a65c635b9e3b6f238eb1de9fe/gradio_demo/app.py#L39) to torch_dtype = torch.float16

Thank you I thought the RTX series would support stuff like that, great that you clarified this. I can confirm that its indeed faster. 
`2 generated images at 1024px and 34 steps = 37minutes.`

**Comment by 4n70w4** [comment]
just for information. rtx 2070: 800 sec for 1 output image with 20 steps. with `torch_dtype = torch.float16`.

**Comment by tomasris** [comment]
Try to reinstall PyTorch with Nvidia support. In my case:
`pip install torch torchvision torchaudio`
`pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124`
It helped for me, now speed is normal.

**Comment by Ishani71199** [comment]
I just have just tried both the version original repo code as well as https://github.com/bmaltais/PhotoMaker/?tab=readme-ov-file#-dependencies-and-installation-windows
I am using NVIDIA RTX 2000 Ada
and the code is even utilizing GPU.
For 4 imgs it is takes me around 40 mins for both. Can someone help me out?

**Comment by Ishani71199** [comment]
> I just have just tried both the version original repo code as well as https://github.com/bmaltais/PhotoMaker/?tab=readme-ov-file#-dependencies-and-installation-windows I am using NVIDIA RTX 2000 Ada and the code is even utilizing GPU. For 4 imgs it is takes me around 40 mins for both. Can someone help me out?

I have just used  NVIDIA RTX A6000 and now it is taking 22 sec for 50steps and 4 image as input.
Thanks
