### ISSUE TITLE
information on project page examples

### ISSUE THREAD

**Issue by badayvedat** [TencentARC/PhotoMaker#50]
amazing work! is it possible for you to share the prompts used for the images in the [Stylization grid in the official project page](https://photo-maker.github.io/)?

<img width="460" alt="image" src="https://github.com/TencentARC/PhotoMaker/assets/54285744/6499ed19-ee33-4178-8ba2-4d548726e4c7">

**Comment by Paper99** [comment]
We use prompts in this [url](https://civitai.com/models/84040?modelVersionId=276923).

**Comment by badayvedat** [comment]
thanks!
