### ISSUE TITLE
hhh, delete issue. 

### ISSUE THREAD

**Issue by JingyuHuAtVoxelCloud** [TencentARC/PhotoMaker#77]
When I upload some male‘s photos and try online demo，PhotoMaker generated male’s photos. But when I try the Newton example, it gives the naked woman photos. I quickly close the browser to avoid embarrassment.

**Comment by rrobert551** [comment]
Are you sure. 

the best [movie 2024](https://moviehd2024.com/)

**Comment by JingyuHuAtVoxelCloud** [comment]
I AM VERY SURE. hhhhh~~

**Comment by JingyuHuAtVoxelCloud** [comment]
> Are you sure.
> 
> the best [movie 2024](https://moviehd2024.com/)
I AM VERY SURE. hhhhh~~

**Comment by Paper99** [comment]
1. Add `nsfw` in `negative prompt`.
2. Add some NSFW check pipeline.

Besides, please read `Broader Impact` section in our paper.
We want AI to be used ethically.

**Comment by JingyuHuAtVoxelCloud** [comment]
> 1. Add `nsfw` in `negative prompt`.
> 2. Add some NSFW check pipeline.
> 
> Besides, please read `Broader Impact` section in our paper. We want AI to be used ethically.

I just provide the commom male's phtoho and try the provided example. Then, the PhotoMaker generated naked photo.
